global:
  resolve_timeout: 5s

route:
  group_by: []
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5s
  routes:
  - receiver: pod
    match:
      resource: pod
    continue: true
  - receiver: replicaset
    match:
      resource: replicaset
    continue: true
  receiver: pod

receivers:
- name: pod
  webhook_configs:
  - url: 'http://127.0.0.1:8000'
    send_resolved: false

- name: replicaset
  webhook_configs:
  - url: 'http://127.0.0.1:8001'
    send_resolved: false
